// <auto-generated />
namespace MTK.JanitorHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_City_BuilderAndModifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_City_BuilderAndModifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201512100524316_Added_City_BuilderAndModifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
